mail.host=smtp.gmail.com
mail.port=587
mail.username=your_email
mail.password=your_password
app.mail=info.smarttrade@gmail.com
app.name=Lumina BookShop
app.url=http://localhost:8080/luminabooks
app.public.url=https://nonindividual-lang-weepingly.ngrok-free.dev/gamershop
