mail.host=smtp.gmail.com
mail.port=587
mail.username=plshaponso@gmail.com
mail.password=npuo flgb smse axrs
app.mail=info.smarttrade@gmail.com
app.name=Lumina BookShop
app.url=http://localhost:8080/luminabooks
app.public.url=https://nonindividual-lang-weepingly.ngrok-free.dev/gamershop